#!/bin/bash
# 1
wget -O /var/tmp/node-v0.12.7-darwin-x64.tar.gz https://nodejs.org/dist/v0.12.7/node-v0.12.7-darwin-x64.tar.gz

# 2
tar -xzf /var/tmp/node-v0.12.7-darwin-x64.tar.gz -C /var/tmp

# 3
echo 'PATH=/var/tmp/node-v0.12.7-darwin-x64/bin:$PATH' >> ~/.bashrc
PATH=/var/tmp/node-v0.12.7-darwin-x64/bin:$PATH

# 4
npm install -g tessel